"""
Alembic migration environment configuration.

Notes on autogenerate behaviour
--------------------------------
``compare_server_default=False``  (intentional)
    ORM models use Python-side ``default=utc_now`` for timestamp columns.
    Earlier autogenerated migrations created those columns with
    ``server_default=sa.text("now()")`` as a safety net.  The two are
    semantically equivalent; comparing them every run produces spurious
    ``ALTER COLUMN ... server_default=None`` noise.

``include_object``  (intentional)
    Several indexes — all trgm GIN indexes, partial indexes, and
    custom operator-class B-tree indexes — are created via raw
    ``op.execute("CREATE INDEX ...")`` in their own dedicated migrations
    because SQLAlchemy's ``Index()`` ORM declaration has limited support for
    PostgreSQL-specific index options (``USING gin``, operator classes,
    ``WHERE`` predicates, expression columns).

    Alembic reflects these indexes from the PostgreSQL catalog but cannot
    match them to any ``Index()`` object in a model's ``__table_args__``.
    It therefore treats them as "extra" and emits ``op.drop_index()`` on
    every autogenerate run.  The filter below suppresses that false-positive
    by ignoring any index that is reflected from the DB but has no
    corresponding model declaration (``compare_to is None``).

    Safe trade-off: every intentional index removal in this codebase is
    handled explicitly in its own migration; we never rely on autogenerate
    to detect index deletions.
"""

import asyncio
from logging.config import fileConfig
from typing import Any

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context
from dotenv import load_dotenv

from app.core.models import Base
from app.core.alembic_models_import import *
from app.core.database import get_database_url

load_dotenv()

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

DATABASE_URL = get_database_url()
config.set_main_option("sqlalchemy.url", DATABASE_URL)


def include_object(
    object: Any,
    name: str,
    type_: str,
    reflected: bool,
    compare_to: Any,
) -> bool:
    """Filter out raw-SQL-managed indexes from autogenerate comparison.

    Indexes created via ``op.execute("CREATE INDEX ...")`` exist in the
    PostgreSQL catalog but have no ``Index()`` declaration in any model,
    so ``compare_to`` is ``None``.  Without this filter Alembic emits a
    ``op.drop_index()`` for every such index on every autogenerate run.
    """
    if type_ == "index" and reflected and compare_to is None:
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in offline mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=False,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=False,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations in online mode with async engine."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
