"""add_release_notes_table

Revision ID: 18da0849f81f
Revises: 5cba55fe1c0f
Create Date: 2026-02-25 07:06:38.087769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18da0849f81f'
down_revision: Union[str, None] = '35fb6f4f87c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_notes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('version', sa.String(length=50), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content_md', sa.Text(), nullable=False),
                    sa.Column('change_type', sa.Enum('feature', 'improvement',
                                                     'bugfix', 'breaking', name='changetype'), nullable=False),
                    sa.Column('is_published', sa.Boolean(), nullable=False),
                    sa.Column('published_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('version')
                    )
    op.create_index('ix_release_notes_published', 'release_notes', [
                    'is_published', 'published_at'], unique=False)
    op.create_index('ix_release_notes_version',
                    'release_notes', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_notes_version', table_name='release_notes')
    op.drop_index('ix_release_notes_published', table_name='release_notes')
    op.drop_table('release_notes')
    # ### end Alembic commands ###
